# Generated by Django 5.0.2 on 2024-03-02 07:48

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blog_categories_remove_blog_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='auth',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default=django.contrib.auth.models.User.get_email_field_name, max_length=200),
        ),
    ]
